import type { Metadata } from "next";
import { Inter } from "next/font/google";
//import "./globals.css";
import "bootstrap/dist/css/bootstrap.min.css"
import React from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}
            style={{transform: "scale(0.9)", transformOrigin: "0 0"}}>{children} </body>
    </html>
  );
}
